Add 주석 컨벤션
DeveloperAcademy-POSTECH/swift-style-guide pull request #28
Opened 2022-06-30 17:46 UTC by Anti9uA

## 카테고리

주석 컨벤션 추가

## 작업 사항

- 함수 및 메서드 관련한 주석 컨벤션을 추가했습니다.

## 설명 및 이유
- 주석은 협업에 있어 다른사람의 코드를 이해하는 중요한 요소인 반면, 통일된 양식이 없고 각자가 생각하는 작성법이 달라서 개발 협업에 어려움을 느꼈었습니다.
- 특히 모듈화에 있어 가장 많이 사용되는 함수와 메서드를 이해하는데 그에 대한 간단한 기능 설명과 파라미터, 그리고 리턴값만 알려줘도 다른 사람의 코드를 이해하는데 훨씬 도움이 될거라 판단했습니다.
- 또한 swift내의 주석은 마크다운 문법과 유사하여 사용하기 편했고 MARK, TODO, FIXME 같이 코드 생산성에 도움을 주는 다양한 주석 기능들이 많았습니다.
- 작은 기여지만 이 한걸음으로부터 아카데미 내 아름다운 주석 작성문화가 정착하길 희망합니다.

## 체크리스트

- [x] 기존에 없는 중복되지 않는 내용
- [x] 개요 및 이유 설명글
- [x] 오탈자 및 문법 확인

2022-07-01 02:09 UTC, taek0622 commented on README.md
> +- 아직 개발이 완료되지 않은 코드가 있다면 TODO나 FIXME를 사용하여 체크하는 것도 좋습니다.
많은 레퍼런스에서 `// MARK: `를 사용하고 있고, 또 현재 작성하신 문서의 다른 주석들은 `/` 뒤에 한칸씩 띄우고 계신 것처럼 일관성을 위해 `//MARK: `나 `//FIXME: `, `//TODO: ` 보다는 `// MARK: `, `// FIXME: `, `// TODO: `는 어떨까요?

### 레퍼런스
- https://google.github.io/swift/#file-comments
- https://github.com/airbnb/swift
- https://github.com/linkedin/swift-style-guide#42-other-commenting-guidelines

2022-07-01 02:23 UTC, Anti9uA commented on README.md
> +- 아직 개발이 완료되지 않은 코드가 있다면 TODO나 FIXME를 사용하여 체크하는 것도 좋습니다.
그렇네요 충분히 일리있는 말씀입니다. 관련 다시 수정해서 커밋했으니 확인 부탁드립니다!

2022-07-01 02:31 UTC, taek0622 commented on README.md
> +        let Malfoy: String
현재 변수 네이밍 규칙에서 변수, 상수 이름은 `lowerCamelCase`로 작성하도록 되어 있습니다.
이 예시에서는 상수 이름이 대문자로 시작되고 있는 것 같은데, 컨벤션에 익숙하지 않으신 분들께 혼란을 야기할 수 있을 것 같습니다.
상수명을 `lowerCamelCase`로 변경해주시면 좋을 것 같습니다~😃

2022-07-01 02:37 UTC, Anti9uA commented on README.md
> +        let Malfoy: String
앗 그렇네요. 수정해서 다시 커밋 업데이트 완료했습니다! 피드백 감사합니다!

2022-07-01 04:55 UTC, taek0622 commented on README.md
> +      }
현재 예시 func에서 어떤 경우에는 () 뒤에 한 칸이 띄워지고 {}가 나오고, 어떤 경우에는 () 뒤에 바로 {}가 나오고 있는 것 같습니다.
혹시 기존 문서 내용과 일관성 있게 () 뒤에 한 칸을 띄고 {}가 나오도록 통일하는 건 어떨까요?😀

2022-07-01 05:22 UTC, Anti9uA commented on README.md
> +      }
넵! 우선 통일성있게 소괄호와 중괄호를 재조정해서 다시 커밋했습니다. 다만 이와같은 괄호 띄어쓰기도 통일성있게 가져가려면 이 또한 새로운 스타일 규정으로 정립해야될 필요가 있어보입니다. 하지만 걱정이 되는건 세세한 띄어쓰기까지 규정이 되어버리면 코드 스타일이 너무 빡빡해지는게 아닌가하는 우려스러운 부분이 있습니다. 이 점 또한 같이 고려 해주셨으면 좋겠습니다. 좋은 피드백 감사합니다! :)

2022-07-01 05:33 UTC, taek0622 approved these changes

2022-07-01 05:33 UTC, taek0622 commented on README.md
> +    /// - Parameter age: user age
혹시 `/`를 세 개 주는 이유가 있나요?
이 코멘트는 수정 요청이 아닌, 단순히 궁금해서 여쭤보는 질문입니다~😀

2022-07-01 06:25 UTC, M1zz commented on README.md
> +    /// - Parameter age: user age
/// 를 쓰면 개행을 했을 때 자동으로 붙지 않아요?

2022-07-01 09:01 UTC, taek0622 commented on README.md
> +    /// - Parameter age: user age
감사합니다. 새로운 지식 하나 얻어갑니다~😄

2022-07-01 09:14 UTC, skycat0212 commented on README.md
> +    /// - Parameter age: user age
해당 방식으로 주석을 작성하면
```
    /// This is Test Function
    /// - Parameters:
    ///   - param1: This is Int Type Parameter
    ///   - param2: This is String Type Parameter
    /// - Returns: return value is Int Type
    func testFunc(param1: Int, param2: String) -> Int {
        return 1
    }
```
<img width="367" alt="스크린샷 2022-07-01 오후 6 13 44" src="https://user-images.githubusercontent.com/20871603/176864748-ff2168d0-81be-4758-9596-20d386035040.png">
<img width="249" alt="스크린샷 2022-07-01 오후 6 14 08" src="https://user-images.githubusercontent.com/20871603/176864857-6899e2d0-2d59-4d2e-b8db-9dc50cb3ba39.png">

이처럼 퀵헬프를 사용할 수 있습니다.

2022-07-01 09:14 UTC, skycat0212 commented on README.md
> +    /// - Parameter age: user age
해당 방식으로 주석을 작성하면
```
    /// This is Test Function
    /// - Parameters:
    ///   - param1: This is Int Type Parameter
    ///   - param2: This is String Type Parameter
    /// - Returns: return value is Int Type
    func testFunc(param1: Int, param2: String) -> Int {
        return 1
    }
```
<img width="367" alt="스크린샷 2022-07-01 오후 6 13 44" src="https://user-images.githubusercontent.com/20871603/176864748-ff2168d0-81be-4758-9596-20d386035040.png">
<img width="249" alt="스크린샷 2022-07-01 오후 6 14 08" src="https://user-images.githubusercontent.com/20871603/176864857-6899e2d0-2d59-4d2e-b8db-9dc50cb3ba39.png">

이처럼 퀵헬프를 사용할 수 있습니다.

2022-07-01 09:25 UTC, skycat0212 reviewed
MARK/TODO/FIXME 와 같은 특수목적의 주석을 제외하면 ```//```주석은 전면 금지시키는 것 같아요.
주석을 최소화하자는 것에는 저도 동의하지만,
언급해주신 MARK/TODO/FIXME의 사례나 퀵헬프용 주석 외에도
함수 내에서의 지역변수에 대한 주석 등 주석이 필요한 사례가 있을 것 같은데,
이에 대해 어떻게 생각하시나요?

2022-07-01 11:11 UTC, M1zz commented
이에 대한 룰도 필요하다고 생각합니다! 먼저 케이스를 정리해볼까요?

/**/ 
//
/// 

위 3가지가 있는데 이 3가지를 모두 사용할 수 있느냐와

사용한다면 언제 사용해야하는지를 컨벤션으로 가져가면 좋을 것 같아요

2022-07-01 12:09 UTC, Anti9uA commented
제 생각은 /**/ 식의 주석은 swift 스타일에서는 배제되는게 맞다고 생각합니다. 주석은 최대한 간결하고 가독성있어야 하기에  /**/  형식의 주석은 불필요한 설명을 야기시킬것으로 예상됩니다. 그리고  /// 스타일은 퀵헬프 메뉴를 사용할수 있기에 class나 struct, 함수나 메소드에 권장하고, // 스타일의 주석은 최대한 지양하는게 좋을것으로 생각됩니다. 이런 문제는 후에 여러 개발자분들이 더 좋은 방향으로 기여해주실것으로 기대하고 있습니다!

2022-07-01 14:49 UTC, M1zz requested changes
수정이 필요하다고 생각되는 부분을 작성해 보았습니다 
의견 부탁드려요

2022-07-01 14:49 UTC, M1zz commented on README.md
> +- 함수와 메소드는 기본적으로 무엇을 하는지 무엇을 반환하는지 설명해주시고,
@Anti9uA 의도하신 부분인가요? 주석을 작성하는 방법에 대한 컨벤션인 것 같아보이는데 함수와 메소드가 무엇인지 꼭 주석으로 적을 필요는 없어보여서요!

함수와 메소드에 대한 주석을 적을 때는 무엇을 하는지, 무엇을 반환하는지를 적어주세요. 널효과?는 무엇인가요 void 반환은 생략한다는게 무엇을 의미하는지 모르겠습니다

2022-07-01 14:49 UTC, M1zz commented on README.md
> +    func readData(ID: Int, name: String) {
ID와 이름을 조합해서 데이터를 불러오는 것 이라면 func readData(from userInfo: UserInfo(ID: Int, name: String) { 이 될 것 같습니다.

함수에 -> Int 가 빠진 것 같습니다

이렇게 주석을 다는 것 보다는 

readUserAge(from userInfo) -> Int 로 함수를 작성하면 주석을 달지 않아도 될까요?

2022-07-01 14:49 UTC, M1zz commented on README.md
> +    // 사용자 데이터 추가
확실히 이런건 bad case 가 맞는 것 같습니다 👏

2022-07-01 14:49 UTC, M1zz commented on README.md
> +      struct Students {
스트럭트 이름에 오타가 있는 것 같습니다 Gryffindor

2022-07-01 14:49 UTC, M1zz commented on README.md
> +      class Slytherin {
갑자기 class가 나와야 할 이유가 있는건가요?

2022-07-01 14:49 UTC, M1zz commented on README.md
> +      // FIXME: - 버그 수정 필요
주석보다는 #warning("버그 수정 필요") 는 어떤가요?

2022-07-02 03:01 UTC, imparang commented on README.md
> +      // FIXME: - 버그 수정 필요
그래서 // FIXME: 와 #warning("")을 같이 쓰는 케이스도 종종 있는 것 같아요

2022-07-02 13:03 UTC, Anti9uA commented on README.md
> +- 함수와 메소드는 기본적으로 무엇을 하는지 무엇을 반환하는지 설명해주시고,
아하 이 부분은 함수나 메소드가 어떤 역할이나 기능을 하는지 간단한 설명이 있었으면 좋겠다 라는 생각애서 작성했습니다. 특히 여러군데에서 사용되거나 내가 작성하지 않은 함수를 다른사람이 사용하게 될 경우 코드를 하나하나 까보며 해석하는게 비효율적이라고 생각했습니다. 그래서 최소한의 주석을 적어준다면 시간이나 코드 생산성에 있어서 훨씬 도움이 될거라 판단했습니다!

2022-07-02 13:03 UTC, Anti9uA commented on README.md
> +    func readData(ID: Int, name: String) {
사실 이 부분을 작성하면서 주석 작성의 간단한 예시를 든거라 크게 무게를 두지 않았습니다. 하지만 적어주신것처럼 함수명과 파라미터를 적게되면 주석을 달지 않고 충분히 가독성있는 코드를 작성하는 좋은 에시인것 같습니다!!

2022-07-02 13:03 UTC, Anti9uA commented on README.md
> +    // 사용자 데이터 추가
감사합니다! 😆

2022-07-02 13:03 UTC, Anti9uA commented on README.md
> +      struct Students {
아닙니다 이름은 오타가 아니라 제대로 작성된것입니다. 하지만 전체적인 내용의 통일성을 생각했을때 수정하는게 맞다 생각됩니다! 이부분은 수정해서 다시 커밋했습니다!

2022-07-02 13:03 UTC, Anti9uA commented on README.md
> +      class Slytherin {
이부분도 예시를 든거라 크게 이유나 의미를 두진 않았습니다!

2022-07-02 13:03 UTC, Anti9uA commented on README.md
> +      // FIXME: - 버그 수정 필요
충분히 일리있는 말씀인거 같습니다. 확실히 버그 수정이 필요한 부분은 #warning으로 사용하는게 맞다고 생각이 됩니다. 그래서 아예 FIXME나 TODO 모두를 warning으로 사용을 통일 시키는 방안에 대해선 어떻게 생각하시나요? 통일성이 생겨서 좋지만 TODO까지 warning으로 사용해야 되나에 대해선 리뷰어분들의 의견이 궁금합니다!

2022-07-03 01:31 UTC, M1zz approved these changes
틀리진 않아서 일단 머지되고 퀄리티 업해도 괜찮을 것 같습니다!

2022-07-03 01:31 UTC, M1zz commented on README.md
> +      // FIXME: - 버그 수정 필요
추후에 개선하면 좋겠네요 이슈 또 따주세요! ㅋㅋㅋ

2022-07-04 06:56 UTC, M1zz commented
다른 분들 의견 주세요!

2022-07-05 12:55 UTC, merged