docs: 띄어쓰기(콜론) 추가
DeveloperAcademy-POSTECH/swift-style-guide pull request #38
Opened 2022-07-05 12:44 UTC by LeeSungNo-ian

- 콜론을 사용할 때의 예시를 만들어 Swift Style Guide에 추가했습니다.

## 카테고리

콜론(`:`)

## 작업 사항

콜론(`:`)을 사용할 땐 콜론의 오른쪽으로 한 칸의 여백을 생성하는 예시를 만들어 포함했습니다.

## 설명 및 이유

콜론(`:`)을 사용할 때의 통일성을 갖추고 싶었습니다.

## 체크리스트

- [X] 기존에 없는 중복되지 않는 내용
- [X] 개요 및 이유 설명글
- [X] 오탈자 및 문법 확인

2022-07-05 13:03 UTC, M1zz requested changes

2022-07-05 13:03 UTC, M1zz commented on README.md
> +- 콜론(`:`)을 사용할 땐 콜론의 오른쪽으로 한 칸의 여백을 생성합니다.
:을 기준으로 오른쪽엔 한 칸 왼쪽은 아무렇게나 상관 없는건가요?

2022-07-05 13:26 UTC, LeeSungNo-ian commented on README.md
> +- 콜론(`:`)을 사용할 땐 콜론의 오른쪽으로 한 칸의 여백을 생성합니다.
오! 좋은 의견 감사합니다.

> 콜론의 왼쪽은 공백없이 코드를 작성합니다. 

피드백 감사합니다. 반영하겠습니다!

2022-07-05 13:42 UTC, JUNY0110 approved these changes
콜론을 생각 못했네요! 감사합니다!

2022-07-05 14:12 UTC, M1zz approved these changes
사소하지만 전 이거 틀리면 엄청 거슬리다고 생각하고 있었던 컨벤션입니다 감사합니다!

2022-07-07 06:51 UTC, taek0622 approved these changes
`:`을 생각 못하고 있었네요. 사소하지만 정말 중요한 컨벤션인 것 같습니다. 감사합니다~😄

2022-07-07 06:53 UTC, merged