Add 메모리 관리 컨벤션
DeveloperAcademy-POSTECH/swift-style-guide pull request #51
Opened 2022-07-10 12:18 UTC by Anti9uA

## 카테고리

메모리 관리

## 작업 사항

순환참조 방지를 위한 weak와 unowned 관련 조항을 추가했습니다.

## 설명 및 이유
- 이번 컨벤션을 작성하면서 메모리 관리라는 까다롭고 어려운 과정을  
어떻게 간결한 컨벤션으로 나타낼수 있을까에 대해 고민이 굉장히 많았습니다.
- 메모리 관리 공부를 하면서 ARC, 객체 수명 연장 방법 등 설명하고 알아야하는 정보들이 많았지만,  
가장 간단한 weak, unowned 참조 방법으로 시작을 떼보려고 합니다.

아직 부족한 부분이 많습니다. 많은 피드백 부탁드립니다 감사합니다.

## 체크리스트

- [x] 기존에 없는 중복되지 않는 내용
- [x] 개요 및 이유 설명글
- [x] 오탈자 및 문법 확인

2022-07-11 01:40 UTC, M1zz commented
와 진짜 쉽지 않네요 다른 분들의 의견도 궁금합니다

2022-07-11 01:46 UTC, unnnyong commented on README.md
> +- 객체 간의 관계를 분석하면서 `weak`와 `unowned`를 사용하여 순환 참조를 방지할 수 있습니다.
```suggestion
- 객체 간의 관계를 분석하면서 `weak`또는 `unowned`를 사용하여 순환 참조를 방지할 수 있습니다.
```

두 개를 모두 사용해야하는 것으로 오해 소지가 있어서 수정을 추천드립니다 ~

2022-07-11 01:50 UTC, unnnyong commented on README.md
> +- 메모리 누수의 원인이 되는 순환 참조가 일어나지 않도록 주의해주세요.
(의견)

Memory leak의 발생 가능성이 높은, (1)protocol을 객체로 선언할 때/(2)Closure에서 self를 사용할 때의 가이드로 포함시키는건 어떨까하는 생각도 드네요 .. !

```swift
// (1)
protocol Challenge {}

final class Academy {
    weka var miniChallnege: Challenge?
}

// (2)
closure = { [weak self] in
    self?.getSomething()
}

2022-07-11 01:55 UTC, M1zz commented on README.md
> +- 메모리 누수의 원인이 되는 순환 참조가 일어나지 않도록 주의해주세요.
이 의견에 저도 동의합니다. 메모린 관리보다 좀 더 큰 카테고리 안에서 메모리 관리 컨벤션이 필요해 보입니다.

2022-07-12 00:50 UTC, Apple-Kong commented on README.md
> +- 메모리 누수의 원인이 되는 순환 참조가 일어나지 않도록 주의해주세요.
저도 동의합니다. 코딩 컨벤션이 컨벤션으로써 역할을 수행하려면, 좋은 내용이지만
'메모리 누수의 원인이 되는 순환 참조가 일어나지 않도록 주의해주세요.'  
와 같은 개념적인 내용 보다는
구체적인 맥락(카테고리) 내에서 구체적인 가이드가 필요해보입니다 😀

2022-07-12 01:50 UTC, M1zz requested changes
커멘트를 확인해 주세요!

2022-07-12 07:14 UTC, Anti9uA commented on README.md
> +- 메모리 누수의 원인이 되는 순환 참조가 일어나지 않도록 주의해주세요.
사실 저도 이번 PR을 작성하면서 워낙 방대하고 난이도 높은 부분을 어디서부터 다뤄야될지 고민을 많이 했습니다. 가장 기본적인 weak, unowned 키워드부터 시작해서 다른분들의 기여를 기대하며 작성했지만, 말씀해주신대로 컨벤션보단 개념적인 요소가 강한것 같습니다!
PR 닫겠습니다!

2022-07-12 08:05 UTC, unnnyong commented
내용은 너무 좋아서 카테고리만 정리되면 Close 하지 않고 반영되어도 좋지 않을까 싶습니다  ,,, !!!! 😢

2022-07-15 00:04 UTC, Lia316 approved these changes
저는 [메모리 관리] 라는 카테고리가 적절하다고 생각합니다

다른 스타일 가이드를 보니까, 스타일이라는 대카테고리 하위 항목으로 있거나, 그대로 메모리 관리 카테고리를 쓰고 있더라고요

메모리 관리의 하위 항목으로 closure, delegate pattern 등에 대한 내용을 넣는다면 자체만으로도 내용이 많아 질 것 같아서 
일단은 해당 카테고리를 유지하고 추후에 비슷한 카테고리끼리 묶어서 대카테고리를 만들면 어떨까요?

일단은 머지되고 추후에 수정되어도 좋을 것 같다고 생각합니다!

2022-07-18 01:03 UTC, M1zz approved these changes
이정도면 충분해 보입니다

추후에 더 정리해보도록 해 보아요

2022-07-18 01:04 UTC, merged