[Edit] 띄어쓰기 -> 들여쓰기 수정
DeveloperAcademy-POSTECH/swift-style-guide pull request #64
Opened 2022-07-18 17:41 UTC by LeeSungNo-ian

## 카테고리
[[내용 수정 및 삭제] <Add 띄어쓰기 #33 -> 들여쓰기로 수정> #39](https://github.com/DeveloperAcademy-POSTECH/swift-style-guide/issues/39)
## 작업 사항
`띄어쓰기` 를 `들여쓰기` 로 수정

## 설명 및 이유
인덴테이션 관련 내용은 들여쓰기가 적합해보입니다.

## 체크리스트
- [x] 기존에 없는 중복되지 않는 내용
- [x] 개요 및 이유 설명글
- [x] 오탈자 및 문법 확인

2022-07-21 14:45 UTC, skycat0212 approved these changes
확인했습니다. 내용에 동의합니다.
다만 Development에 해당 이슈 연결 부탁드립니다.

2022-07-23 13:10 UTC, taek0622 commented on README.md
> +## 띄어쓰기
해당 부분이 들여쓰기와 띄어쓰기로 나누어진다면, 목차도 그에 맞게 수정이 필요할 것 같습니다.

2022-07-25 11:26 UTC, Lia316 requested changes
저도 동의합니다!
다만, taek0622 님이 말씀하신 대로 목차 수정이 필요해 보이네요!

2022-07-27 11:22 UTC, JUNY0110 commented
Assignee 드렸습니다!

2022-07-27 11:23 UTC, JUNY0110 approved these changes

2022-08-17 01:28 UTC, M1zz approved these changes
lgtm

2022-08-17 01:28 UTC, M1zz commented on README.md
> +## 띄어쓰기
꼼꼼한 리뷰 감사합니다

2022-08-17 01:28 UTC, merged