[add] #52 <네이밍-델리게이트>
DeveloperAcademy-POSTECH/swift-style-guide pull request #65
Opened 2022-07-30 07:53 UTC by yoo86

## 카테고리

Naming of Delegates

## 작업 사항

델리게이트 네이밍 규칙

## 설명 및 이유

- 델리게이트의 네임스페이스는 프로토콜명으로 구분합니다. -> swift에서는 델리게이트를 class와 protocol로 구현할 수 있지만, class 형태로 객체를 넘겨주게 되면 동일한 delegate를 사용하기 위해선 반드시 상속을 받아야 하기 때문에 protocol로만 구현하도록 컨벤션을 작성했습니다.
- 델리게이트의 소스 객체만을 메서드의 인자로 받는 경우와 추가적인 인자도 함께 받는 경우를 구분하여 함수명을 작성하도록 했습니다.

## 체크리스트

- [x] 기존에 없는 중복되지 않는 내용
- [x] 개요 및 이유 설명글
- [x] 오탈자 및 문법 확인

2022-08-07 13:46 UTC, skycat0212 requested changes
고생하셨습니다!

2022-08-07 13:46 UTC, skycat0212 commented on README.md
> +                func UserScrollView(_ scrollView: UIScrollView)
해당 사례가 Bad의 사례인 이유가 UpperCamelCase인 것과 함수의 이름과 파라미터 만으로는 함수로서의 의미를 알 수 없게 모호한 것으로 2가지 이상인 것 같습니다. 이런 경우 독자가 Bad의 사례를 명확히 이해하도록 하기 위해 하나의 사례는 하나의 이유만을 담게 하는 것은 어떨까요?

2022-08-09 06:15 UTC, yoo86 commented on README.md
> +                func UserScrollView(_ scrollView: UIScrollView)
하나의 사례만을 담아야 한다는 것이 하나의 protocol에 잘못된 예시를 하나만 넣어야 된다는 건가요?

2022-08-17 01:33 UTC, M1zz requested changes
배드 케이스가 더 잘 도드라지도록 수정 부탁드릴게요

2022-08-17 01:33 UTC, M1zz commented on README.md
> +                func UserScrollView(_ scrollView: UIScrollView)
무엇때문에 Bad 케이스 인지알기가 어렵다는 것 같네요
1. func UserScrollView -> 대문자라서 bad 케이스인가
2. func UserScrollView(_ scrollView: UIScrollView) 첫번째 인자는 생략 가능한데 왜 배드케이스 인지 헷갈립니다

2022-08-28 12:04 UTC, yoo86 commented
[507514e](https://github.com/DeveloperAcademy-POSTECH/swift-style-guide/pull/65/commits/507514e9966bd312904199426aff65ef234e9e26)
bad case에 설명 추가했습니다~

2022-12-14 07:30 UTC, merged